language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - CARGO_ARGS=""

matrix:
  include:
    - rust: nightly
      env: CARGO_ARGS="--features clippy"
  exclude:
    - rust: nightly

before_script: (cargo install rustfmt || true)

script:
  - set -e
  - export PATH="${PATH}:${HOME}/.cargo/bin"
  - export RUST_BACKTRACE=1
  - cargo fmt -- --write-mode=diff
  - cargo build ${CARGO_ARGS} --verbose --bin iwls
  - cargo test ${CARGO_ARGS} --verbose --bin iwls
  - cargo run ${CARGO_ARGS} --verbose --bin iwls

after_success:
  - scripts/build_kcov.sh
  - scripts/send_kcov.sh
  - bash <(curl -s https://codecov.io/bash)
