language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add rustfmt clippy

script:
  - set -e
  - export PATH="${PATH}:${HOME}/.cargo/bin"
  - export RUST_BACKTRACE=1
  - cargo fmt -- --write-mode=diff
  - cargo clippy -- -D warnings
  - cargo build --verbose
  - cargo test --verbose
  - cargo run --verbose --bin iwls

after_success:
  - scripts/build_kcov.sh
  - scripts/send_kcov.sh
  - bash <(curl -s https://codecov.io/bash)
